spring.application.name=porttrack
# ===============================
# DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/port_track?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=porttrack
spring.datasource.password=Anhthu1605
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# Tự động update schema database dựa trên Entity tắt 
spring.jpa.hibernate.ddl-auto=none 
# In ra console các câu lệnh SQL để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Đổi cổng chạy server
server.port=8081